acme_blog_post_admin:
    pattern:  /
    defaults: { _controller: "AcmeBlogBundle:AdminPost:index" }

acme_blog_post_new:
    pattern:  /new
    defaults: { _controller: "AcmeBlogBundle:AdminPost:new" }

acme_blog_post_create:
    pattern:  /create
    defaults: { _controller: "AcmeBlogBundle:AdminPost:create" }
    requirements: { _method: post }

acme_blog_post_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AcmeBlogBundle:AdminPost:edit" }

acme_blog_post_update:
    pattern:  /{id}/update
    defaults: { _controller: "AcmeBlogBundle:AdminPost:update" }
    requirements: { _method: post|put }

acme_blog_post_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AcmeBlogBundle:AdminPost:delete" }
